apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  DB_HOST: "ecommercedb.catc86eyes0c.us-east-1.rds.amazonaws.com"
  DB_PORT: "3306"
  DB_NAME: "ecommercedb"
  DB_USER: "admin"
  DYNAMODB_TABLE: "ecommerce-products"
  AWS_REGION: "us-east-1"
  S3_BUCKET_NAME: "ecommerce-data-bucket-129257836401"
  KAFKA_BOOTSTRAP_SERVERS: "b-1.ecommercekafka.sexwyl.c6.kafka.us-east-1.amazonaws.com:9094,b-2.ecommercekafka.sexwyl.c6.kafka.us-east-1.amazonaws.com:9094"
  KAFKA_SECURITY_PROTOCOL: "SSL"
  KAFKA_SSL_CAFILE: "/etc/ssl/certs/ca-certificates.crt"
  KAFKA_API_VERSION: "3.5.1"
  USER_SERVICE_URL: "http://user-service:5001"
  PRODUCT_SERVICE_URL: "http://product-service:5002"
  ORDER_SERVICE_URL: "http://order-service:5003"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
type: Opaque
stringData:
  DB_PASSWORD: "Admin123456!"
